#!/bin/bash
#
#

set -e

_install() {
    local pkg=$1 ver=$2 afterhook=$3

    echo "installing $pkg $ver"

    cd /tmp

    # Download the snapshot
    wget -q https://github.com/thumbor/$pkg/archive/${ver}.zip && \
        unzip ${ver}.zip >/dev/null && rm -f ${ver}.zip

    cd "$pkg-${ver}"

    if [ -e "requirements" ]; then
        apt-get install \
            --ignore-missing --fix-broken -y \
                $(cat requirements)
    fi

    python setup.py install

    if [ -n "$afterhook" ]; then
        $afterhook
    fi

    cd /
    rm -rf "/tmp/$pkg-${ver}"
}

_install_thumbor() {
    cp -f debian/thumbor.conf /etc/thumbor.conf
}

_install thumbor $THUMBOR_VERSION _install_thumbor

if [ "${THUMBOR_ENGINE}" = "opencv" ]; then
    _install opencv-engine $OPENCV_ENGINE_VERSION
elif [ "${THUMBOR_ENGINE}" = "graphicsmagick" ]; then
    _install graphicsmagick-engine $GRAPHICSMAGICK_ENGINE_VERSION
elif [ "${THUMBOR_ENGINE}" = "pil" ]; then
    echo "PIL is built in"
else
    echo "ERROR: Unsupported thumbor engine: ${THUMBOR_ENGINE}" >&2
    exit 1
fi
